export { default as Admin } from './src/admin.vue'
export { default as Resource } from './src/resource.vue'
export { default as ResourceForm } from './src/resource-form.vue'

export { default as Button } from './src/button.vue'
export { default as Card } from './src/card.vue'
export { default as Editor } from './src/editor.vue'
export { default as Field } from './src/field.vue'
export { default as Icon } from './src/icon.vue'
export { default as ImageUploader } from './src/image-uploader.vue'
export { default as Message } from './src/message.vue'
export { default as Select } from './src/select.vue'
export { default as Input } from './src/input.vue'
export { default as Switcher } from './src/switcher.vue'